name: Tests Python

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Lancer les tests en mode détaillé
        run: python3 -m test/test1 -v
